config/routes.rb
Rails.application.routes.draw do
  get 'about', to:'about#index'

  get 'password', to: 'passwords#edit', as: :edit_password
  patch 'password', to: 'passwords#update'

  # sign up route
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  # sign in route
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'

  # logout route
  delete 'logout', to: 'sessions#destroy'

  # password reset 
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  # route route
  root to:'main#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/user.rb
# email : string 
# password_digest :string
# password : string
# password_confirmation: string 

# for authentication >      user.authenticate

class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true, uniqueness: { case_sensitive: false }, length: {maximum: 50}, format: { with: /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/ }
    
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index 
        
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    def set_current_user
        if session[:user_id] 
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def require_user_logged_in!
        redirect_to sign_in_path, alert: "you must signed in to do that first." if Current.user.nil?
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

    def index 
        # flash.now[:notice] = " Logged in Successfully"
        # flash.now[:alert] = " Invalid Username And password"

        # set this inside application controller for use multiple times
        # if session[:user_id] 
        #     # @user = User.find(session[:user_id])
        #     @user = User.find_by(id: session[:user_id])
        # end
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new
    end

    def create
        @user = User.find_by(email: params[:email])

        if @user.present?
            # send email 
            PasswordMailer.with(user: @user).reset.deliver_now
        else
            redirect_to root_path, notice: 'If an account with that email we found, we have set a link to reset your passwrod'
        end
    end  

    def edit
        @user = User.find_signed!(params[:token], purpose: "password_reset")  
    rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to sign_in_path, alert: "your token has expired, please try again"
    end

    def update
        @user = User.find_signed!(params[:token], purpose: "password_reset")  
        if @user.update(password_params)
            redirect_to sign_in_path, notice: " Your password was reset successfully , please sign in"
        else
            render :edit
        end
    end

    private 
    
    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController 
    before_action :require_user_logged_in!
    def edit 

    end
    def update 
       if Current.user.update(password_params)
        redirect_to root_path, notice: "password updated successfully"
       else
        render :edit
       end

    end

    private
    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
    
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
        @user = User.new
    end

    def create 
        # render plain:"Thanks"
        # render plain: params[:user]
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Successfully Created Account"
        else
            render :new
        end
    end

    private
    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def def new
       
    end

    def create 
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Logged In Successfully"
        else
            flash[:alert] = "Invalid Credentials"
            render :new
        end
    end
    
    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged Out"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>hello world</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnRails</title>

    <!-- Bootstrap cdn links -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h1> Welcome To Scheduled Tweets </h1>
</div>

app/views/password_resets/edit.html.erb
<h1> Reset Your Password </h1>

<%= form_with model: @user ,url: password_reset_edit_path(token: params[:token]) do |form| %>

    <% if form.object.errors.any? %>
        <div class="alert alert-danger">
            <% form.object.errors.full_messages.each do |msg| %>
                <div>
                    <%= msg %>
                </div>
                <% end %>
        </div>
        <% end %>

            <div class="mb-3">
                <%= form.label :password %>
                    <%= form.password_field :password, class:'form-control', placeholder:'password' %>
            </div>
            <div class="mb-3">
                <%= form.label :password_confirmation %>
                    <%= form.password_field :password_confirmation, class:'form-control',
                        placeholder: 'confirm your password' %>
            </div>
            <div class="mb-3">
                <%= form.submit "Reset Password" , class: "btn btn-primary" %>
            </div>
            <% end %>

app/views/password_resets/new.html.erb
<h1> Forget Your Password</h1>

<%= form_with url: password_reset_path do |form| %>
<div class="mb-3">
    <%= form.label :email %>
        <%= form.text_field :email, class:'form-control', placeholder:'your-email@example.com' %>
</div>
<div class="mb-3">
    <%= form.submit "Reset password" , class:'btn btn-primary' %>
</div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice]%>
<div class="alert alert-primary alert-dismissible fade show" role="alert">
   <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

<% if flash[:alert]%>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= flash[:alert] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Rails" , root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Home" , root_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "About" , about_path, class: "nav-link" %>
          </li>
        </ul>

        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <% if Current.user %>
            <li class="nav-item">
              <%= link_to Current.user.email, edit_password_path, class:'nav-link' %>
            </li>
            <li class="nav-item">
              <%= button_to "Logout" , logout_path, method: :delete, class:'btn  btn-outline-secondary' %>
            </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Sign Up" , sign_up_path, class:'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to "Login" , sign_in_path, class:'nav-link' %>
              </li>
              <% end %>
        </ul>

      </div>
  </div>
</nav>